//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace PandPMobileApp.PandPNameSpace {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResult", Namespace="DomainServices")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.QueryResultOfsysdiagrams))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.QueryResultOfTraffic))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.QueryResultOfMembers))]
    public partial class QueryResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int TotalCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResultOfsysdiagrams", Namespace="DomainServices")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.QueryResultOfMembers))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.QueryResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.DomainServiceFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ValidationResultInfo>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.ValidationResultInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.QueryResultOfTraffic))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ChangeSetEntry>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.ChangeSetEntry))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.DomainOperation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.Members))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.sysdiagrams))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.Traffic))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.Members>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.sysdiagrams>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.Traffic>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<int>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<int>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<object>>))]
    public partial class QueryResultOfsysdiagrams : PandPMobileApp.PandPNameSpace.QueryResult {
        
        private System.Collections.ObjectModel.ObservableCollection<object> IncludedResultsField;
        
        private System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.sysdiagrams> RootResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<object> IncludedResults {
            get {
                return this.IncludedResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.IncludedResultsField, value) != true)) {
                    this.IncludedResultsField = value;
                    this.RaisePropertyChanged("IncludedResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.sysdiagrams> RootResults {
            get {
                return this.RootResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.RootResultsField, value) != true)) {
                    this.RootResultsField = value;
                    this.RaisePropertyChanged("RootResults");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResultOfTraffic", Namespace="DomainServices")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.QueryResultOfMembers))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.QueryResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.DomainServiceFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ValidationResultInfo>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.ValidationResultInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.QueryResultOfsysdiagrams))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ChangeSetEntry>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.ChangeSetEntry))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.DomainOperation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.Members))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.sysdiagrams))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.Traffic))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.Members>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.sysdiagrams>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.Traffic>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<int>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<int>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<object>>))]
    public partial class QueryResultOfTraffic : PandPMobileApp.PandPNameSpace.QueryResult {
        
        private System.Collections.ObjectModel.ObservableCollection<object> IncludedResultsField;
        
        private System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.Traffic> RootResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<object> IncludedResults {
            get {
                return this.IncludedResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.IncludedResultsField, value) != true)) {
                    this.IncludedResultsField = value;
                    this.RaisePropertyChanged("IncludedResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.Traffic> RootResults {
            get {
                return this.RootResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.RootResultsField, value) != true)) {
                    this.RootResultsField = value;
                    this.RaisePropertyChanged("RootResults");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryResultOfMembers", Namespace="DomainServices")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.QueryResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.DomainServiceFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ValidationResultInfo>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.ValidationResultInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.QueryResultOfsysdiagrams))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.QueryResultOfTraffic))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ChangeSetEntry>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.ChangeSetEntry))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.DomainOperation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.Members))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.sysdiagrams))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.Traffic))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.Members>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.sysdiagrams>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.Traffic>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<int>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<int>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<object>>))]
    public partial class QueryResultOfMembers : PandPMobileApp.PandPNameSpace.QueryResult {
        
        private System.Collections.ObjectModel.ObservableCollection<object> IncludedResultsField;
        
        private System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.Members> RootResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<object> IncludedResults {
            get {
                return this.IncludedResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.IncludedResultsField, value) != true)) {
                    this.IncludedResultsField = value;
                    this.RaisePropertyChanged("IncludedResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.Members> RootResults {
            get {
                return this.RootResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.RootResultsField, value) != true)) {
                    this.RootResultsField = value;
                    this.RaisePropertyChanged("RootResults");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DomainServiceFault", Namespace="DomainServices")]
    public partial class DomainServiceFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ErrorCodeField;
        
        private string ErrorMessageField;
        
        private bool IsDomainExceptionField;
        
        private System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ValidationResultInfo> OperationErrorsField;
        
        private string StackTraceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDomainException {
            get {
                return this.IsDomainExceptionField;
            }
            set {
                if ((this.IsDomainExceptionField.Equals(value) != true)) {
                    this.IsDomainExceptionField = value;
                    this.RaisePropertyChanged("IsDomainException");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ValidationResultInfo> OperationErrors {
            get {
                return this.OperationErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationErrorsField, value) != true)) {
                    this.OperationErrorsField = value;
                    this.RaisePropertyChanged("OperationErrors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationResultInfo", Namespace="DomainServices")]
    public partial class ValidationResultInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ErrorCodeField;
        
        private string MessageField;
        
        private System.Collections.ObjectModel.ObservableCollection<string> SourceMemberNamesField;
        
        private string StackTraceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<string> SourceMemberNames {
            get {
                return this.SourceMemberNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceMemberNamesField, value) != true)) {
                    this.SourceMemberNamesField = value;
                    this.RaisePropertyChanged("SourceMemberNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangeSetEntry", Namespace="DomainServices")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.QueryResultOfMembers))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.QueryResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.DomainServiceFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ValidationResultInfo>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.ValidationResultInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.QueryResultOfsysdiagrams))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.QueryResultOfTraffic))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ChangeSetEntry>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.DomainOperation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.Members))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.sysdiagrams))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PandPMobileApp.PandPNameSpace.Traffic))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.Members>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.sysdiagrams>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.Traffic>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<int>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<int>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<object>>))]
    public partial class ChangeSetEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<int>> AssociationsField;
        
        private System.Collections.ObjectModel.ObservableCollection<string> ConflictMembersField;
        
        private object EntityField;
        
        private System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<object>> EntityActionsField;
        
        private bool HasMemberChangesField;
        
        private int IdField;
        
        private bool IsDeleteConflictField;
        
        private PandPMobileApp.PandPNameSpace.DomainOperation OperationField;
        
        private System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<int>> OriginalAssociationsField;
        
        private object OriginalEntityField;
        
        private object StoreEntityField;
        
        private System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ValidationResultInfo> ValidationErrorsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<int>> Associations {
            get {
                return this.AssociationsField;
            }
            set {
                if ((object.ReferenceEquals(this.AssociationsField, value) != true)) {
                    this.AssociationsField = value;
                    this.RaisePropertyChanged("Associations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<string> ConflictMembers {
            get {
                return this.ConflictMembersField;
            }
            set {
                if ((object.ReferenceEquals(this.ConflictMembersField, value) != true)) {
                    this.ConflictMembersField = value;
                    this.RaisePropertyChanged("ConflictMembers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Entity {
            get {
                return this.EntityField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityField, value) != true)) {
                    this.EntityField = value;
                    this.RaisePropertyChanged("Entity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<object>> EntityActions {
            get {
                return this.EntityActionsField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityActionsField, value) != true)) {
                    this.EntityActionsField = value;
                    this.RaisePropertyChanged("EntityActions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasMemberChanges {
            get {
                return this.HasMemberChangesField;
            }
            set {
                if ((this.HasMemberChangesField.Equals(value) != true)) {
                    this.HasMemberChangesField = value;
                    this.RaisePropertyChanged("HasMemberChanges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool IsDeleteConflict {
            get {
                return this.IsDeleteConflictField;
            }
            set {
                if ((this.IsDeleteConflictField.Equals(value) != true)) {
                    this.IsDeleteConflictField = value;
                    this.RaisePropertyChanged("IsDeleteConflict");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PandPMobileApp.PandPNameSpace.DomainOperation Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((this.OperationField.Equals(value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.ObservableCollection<int>> OriginalAssociations {
            get {
                return this.OriginalAssociationsField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalAssociationsField, value) != true)) {
                    this.OriginalAssociationsField = value;
                    this.RaisePropertyChanged("OriginalAssociations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object OriginalEntity {
            get {
                return this.OriginalEntityField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalEntityField, value) != true)) {
                    this.OriginalEntityField = value;
                    this.RaisePropertyChanged("OriginalEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object StoreEntity {
            get {
                return this.StoreEntityField;
            }
            set {
                if ((object.ReferenceEquals(this.StoreEntityField, value) != true)) {
                    this.StoreEntityField = value;
                    this.RaisePropertyChanged("StoreEntity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ValidationResultInfo> ValidationErrors {
            get {
                return this.ValidationErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidationErrorsField, value) != true)) {
                    this.ValidationErrorsField = value;
                    this.RaisePropertyChanged("ValidationErrors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DomainOperation", Namespace="DomainServices")]
    public enum DomainOperation : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Query = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Insert = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Custom = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invoke = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Members", Namespace="http://schemas.datacontract.org/2004/07/PandPproject.Web.Models")]
    public partial class Members : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string EmailField;
        
        private int IDField;
        
        private string NameField;
        
        private string PasswordField;
        
        private string RankField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rank {
            get {
                return this.RankField;
            }
            set {
                if ((object.ReferenceEquals(this.RankField, value) != true)) {
                    this.RankField = value;
                    this.RaisePropertyChanged("Rank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="sysdiagrams", Namespace="http://schemas.datacontract.org/2004/07/PandPproject.Web.Models")]
    public partial class sysdiagrams : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] definitionField;
        
        private int diagram_idField;
        
        private string nameField;
        
        private int principal_idField;
        
        private System.Nullable<int> versionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] definition {
            get {
                return this.definitionField;
            }
            set {
                if ((object.ReferenceEquals(this.definitionField, value) != true)) {
                    this.definitionField = value;
                    this.RaisePropertyChanged("definition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int diagram_id {
            get {
                return this.diagram_idField;
            }
            set {
                if ((this.diagram_idField.Equals(value) != true)) {
                    this.diagram_idField = value;
                    this.RaisePropertyChanged("diagram_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int principal_id {
            get {
                return this.principal_idField;
            }
            set {
                if ((this.principal_idField.Equals(value) != true)) {
                    this.principal_idField = value;
                    this.RaisePropertyChanged("principal_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> version {
            get {
                return this.versionField;
            }
            set {
                if ((this.versionField.Equals(value) != true)) {
                    this.versionField = value;
                    this.RaisePropertyChanged("version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Traffic", Namespace="http://schemas.datacontract.org/2004/07/PandPproject.Web.Models")]
    public partial class Traffic : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<System.DateTime> ArrivalField;
        
        private System.Nullable<System.DateTime> DepartureField;
        
        private System.Nullable<int> GPSPickUpField;
        
        private int IDField;
        
        private int MemberIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Arrival {
            get {
                return this.ArrivalField;
            }
            set {
                if ((this.ArrivalField.Equals(value) != true)) {
                    this.ArrivalField = value;
                    this.RaisePropertyChanged("Arrival");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Departure {
            get {
                return this.DepartureField;
            }
            set {
                if ((this.DepartureField.Equals(value) != true)) {
                    this.DepartureField = value;
                    this.RaisePropertyChanged("Departure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GPSPickUp {
            get {
                return this.GPSPickUpField;
            }
            set {
                if ((this.GPSPickUpField.Equals(value) != true)) {
                    this.GPSPickUpField = value;
                    this.RaisePropertyChanged("GPSPickUp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MemberID {
            get {
                return this.MemberIDField;
            }
            set {
                if ((this.MemberIDField.Equals(value) != true)) {
                    this.MemberIDField = value;
                    this.RaisePropertyChanged("MemberID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PandPNameSpace.PandPDomainServicesoap")]
    public interface PandPDomainServicesoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/PandPDomainServicesoap/GetMembers", ReplyAction="http://tempuri.org/PandPDomainServicesoap/GetMembersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PandPMobileApp.PandPNameSpace.DomainServiceFault), Action="http://tempuri.org/PandPDomainServicesoap/GetMembersDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        System.IAsyncResult BeginGetMembers(System.AsyncCallback callback, object asyncState);
        
        PandPMobileApp.PandPNameSpace.QueryResultOfMembers EndGetMembers(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/PandPDomainServicesoap/GetSysdiagrams", ReplyAction="http://tempuri.org/PandPDomainServicesoap/GetSysdiagramsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PandPMobileApp.PandPNameSpace.DomainServiceFault), Action="http://tempuri.org/PandPDomainServicesoap/GetSysdiagramsDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        System.IAsyncResult BeginGetSysdiagrams(System.AsyncCallback callback, object asyncState);
        
        PandPMobileApp.PandPNameSpace.QueryResultOfsysdiagrams EndGetSysdiagrams(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/PandPDomainServicesoap/GetTraffic", ReplyAction="http://tempuri.org/PandPDomainServicesoap/GetTrafficResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PandPMobileApp.PandPNameSpace.DomainServiceFault), Action="http://tempuri.org/PandPDomainServicesoap/GetTrafficDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        System.IAsyncResult BeginGetTraffic(System.AsyncCallback callback, object asyncState);
        
        PandPMobileApp.PandPNameSpace.QueryResultOfTraffic EndGetTraffic(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/PandPDomainServicesoap/SubmitChanges", ReplyAction="http://tempuri.org/PandPDomainServicesoap/SubmitChangesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PandPMobileApp.PandPNameSpace.DomainServiceFault), Action="http://tempuri.org/PandPDomainServicesoap/SubmitChangesDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
        System.IAsyncResult BeginSubmitChanges(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ChangeSetEntry> changeSet, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ChangeSetEntry> EndSubmitChanges(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PandPDomainServicesoapChannel : PandPMobileApp.PandPNameSpace.PandPDomainServicesoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetMembersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetMembersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PandPMobileApp.PandPNameSpace.QueryResultOfMembers Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PandPMobileApp.PandPNameSpace.QueryResultOfMembers)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSysdiagramsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSysdiagramsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PandPMobileApp.PandPNameSpace.QueryResultOfsysdiagrams Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PandPMobileApp.PandPNameSpace.QueryResultOfsysdiagrams)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTrafficCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTrafficCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PandPMobileApp.PandPNameSpace.QueryResultOfTraffic Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PandPMobileApp.PandPNameSpace.QueryResultOfTraffic)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubmitChangesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SubmitChangesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ChangeSetEntry> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ChangeSetEntry>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PandPDomainServicesoapClient : System.ServiceModel.ClientBase<PandPMobileApp.PandPNameSpace.PandPDomainServicesoap>, PandPMobileApp.PandPNameSpace.PandPDomainServicesoap {
        
        private BeginOperationDelegate onBeginGetMembersDelegate;
        
        private EndOperationDelegate onEndGetMembersDelegate;
        
        private System.Threading.SendOrPostCallback onGetMembersCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSysdiagramsDelegate;
        
        private EndOperationDelegate onEndGetSysdiagramsDelegate;
        
        private System.Threading.SendOrPostCallback onGetSysdiagramsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTrafficDelegate;
        
        private EndOperationDelegate onEndGetTrafficDelegate;
        
        private System.Threading.SendOrPostCallback onGetTrafficCompletedDelegate;
        
        private BeginOperationDelegate onBeginSubmitChangesDelegate;
        
        private EndOperationDelegate onEndSubmitChangesDelegate;
        
        private System.Threading.SendOrPostCallback onSubmitChangesCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public PandPDomainServicesoapClient() {
        }
        
        public PandPDomainServicesoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PandPDomainServicesoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PandPDomainServicesoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PandPDomainServicesoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetMembersCompletedEventArgs> GetMembersCompleted;
        
        public event System.EventHandler<GetSysdiagramsCompletedEventArgs> GetSysdiagramsCompleted;
        
        public event System.EventHandler<GetTrafficCompletedEventArgs> GetTrafficCompleted;
        
        public event System.EventHandler<SubmitChangesCompletedEventArgs> SubmitChangesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PandPMobileApp.PandPNameSpace.PandPDomainServicesoap.BeginGetMembers(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetMembers(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PandPMobileApp.PandPNameSpace.QueryResultOfMembers PandPMobileApp.PandPNameSpace.PandPDomainServicesoap.EndGetMembers(System.IAsyncResult result) {
            return base.Channel.EndGetMembers(result);
        }
        
        private System.IAsyncResult OnBeginGetMembers(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PandPMobileApp.PandPNameSpace.PandPDomainServicesoap)(this)).BeginGetMembers(callback, asyncState);
        }
        
        private object[] OnEndGetMembers(System.IAsyncResult result) {
            PandPMobileApp.PandPNameSpace.QueryResultOfMembers retVal = ((PandPMobileApp.PandPNameSpace.PandPDomainServicesoap)(this)).EndGetMembers(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetMembersCompleted(object state) {
            if ((this.GetMembersCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetMembersCompleted(this, new GetMembersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetMembersAsync() {
            this.GetMembersAsync(null);
        }
        
        public void GetMembersAsync(object userState) {
            if ((this.onBeginGetMembersDelegate == null)) {
                this.onBeginGetMembersDelegate = new BeginOperationDelegate(this.OnBeginGetMembers);
            }
            if ((this.onEndGetMembersDelegate == null)) {
                this.onEndGetMembersDelegate = new EndOperationDelegate(this.OnEndGetMembers);
            }
            if ((this.onGetMembersCompletedDelegate == null)) {
                this.onGetMembersCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetMembersCompleted);
            }
            base.InvokeAsync(this.onBeginGetMembersDelegate, null, this.onEndGetMembersDelegate, this.onGetMembersCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PandPMobileApp.PandPNameSpace.PandPDomainServicesoap.BeginGetSysdiagrams(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSysdiagrams(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PandPMobileApp.PandPNameSpace.QueryResultOfsysdiagrams PandPMobileApp.PandPNameSpace.PandPDomainServicesoap.EndGetSysdiagrams(System.IAsyncResult result) {
            return base.Channel.EndGetSysdiagrams(result);
        }
        
        private System.IAsyncResult OnBeginGetSysdiagrams(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PandPMobileApp.PandPNameSpace.PandPDomainServicesoap)(this)).BeginGetSysdiagrams(callback, asyncState);
        }
        
        private object[] OnEndGetSysdiagrams(System.IAsyncResult result) {
            PandPMobileApp.PandPNameSpace.QueryResultOfsysdiagrams retVal = ((PandPMobileApp.PandPNameSpace.PandPDomainServicesoap)(this)).EndGetSysdiagrams(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSysdiagramsCompleted(object state) {
            if ((this.GetSysdiagramsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSysdiagramsCompleted(this, new GetSysdiagramsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSysdiagramsAsync() {
            this.GetSysdiagramsAsync(null);
        }
        
        public void GetSysdiagramsAsync(object userState) {
            if ((this.onBeginGetSysdiagramsDelegate == null)) {
                this.onBeginGetSysdiagramsDelegate = new BeginOperationDelegate(this.OnBeginGetSysdiagrams);
            }
            if ((this.onEndGetSysdiagramsDelegate == null)) {
                this.onEndGetSysdiagramsDelegate = new EndOperationDelegate(this.OnEndGetSysdiagrams);
            }
            if ((this.onGetSysdiagramsCompletedDelegate == null)) {
                this.onGetSysdiagramsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSysdiagramsCompleted);
            }
            base.InvokeAsync(this.onBeginGetSysdiagramsDelegate, null, this.onEndGetSysdiagramsDelegate, this.onGetSysdiagramsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PandPMobileApp.PandPNameSpace.PandPDomainServicesoap.BeginGetTraffic(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTraffic(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PandPMobileApp.PandPNameSpace.QueryResultOfTraffic PandPMobileApp.PandPNameSpace.PandPDomainServicesoap.EndGetTraffic(System.IAsyncResult result) {
            return base.Channel.EndGetTraffic(result);
        }
        
        private System.IAsyncResult OnBeginGetTraffic(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PandPMobileApp.PandPNameSpace.PandPDomainServicesoap)(this)).BeginGetTraffic(callback, asyncState);
        }
        
        private object[] OnEndGetTraffic(System.IAsyncResult result) {
            PandPMobileApp.PandPNameSpace.QueryResultOfTraffic retVal = ((PandPMobileApp.PandPNameSpace.PandPDomainServicesoap)(this)).EndGetTraffic(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTrafficCompleted(object state) {
            if ((this.GetTrafficCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTrafficCompleted(this, new GetTrafficCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTrafficAsync() {
            this.GetTrafficAsync(null);
        }
        
        public void GetTrafficAsync(object userState) {
            if ((this.onBeginGetTrafficDelegate == null)) {
                this.onBeginGetTrafficDelegate = new BeginOperationDelegate(this.OnBeginGetTraffic);
            }
            if ((this.onEndGetTrafficDelegate == null)) {
                this.onEndGetTrafficDelegate = new EndOperationDelegate(this.OnEndGetTraffic);
            }
            if ((this.onGetTrafficCompletedDelegate == null)) {
                this.onGetTrafficCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTrafficCompleted);
            }
            base.InvokeAsync(this.onBeginGetTrafficDelegate, null, this.onEndGetTrafficDelegate, this.onGetTrafficCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PandPMobileApp.PandPNameSpace.PandPDomainServicesoap.BeginSubmitChanges(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ChangeSetEntry> changeSet, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSubmitChanges(changeSet, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ChangeSetEntry> PandPMobileApp.PandPNameSpace.PandPDomainServicesoap.EndSubmitChanges(System.IAsyncResult result) {
            return base.Channel.EndSubmitChanges(result);
        }
        
        private System.IAsyncResult OnBeginSubmitChanges(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ChangeSetEntry> changeSet = ((System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ChangeSetEntry>)(inValues[0]));
            return ((PandPMobileApp.PandPNameSpace.PandPDomainServicesoap)(this)).BeginSubmitChanges(changeSet, callback, asyncState);
        }
        
        private object[] OnEndSubmitChanges(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ChangeSetEntry> retVal = ((PandPMobileApp.PandPNameSpace.PandPDomainServicesoap)(this)).EndSubmitChanges(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSubmitChangesCompleted(object state) {
            if ((this.SubmitChangesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SubmitChangesCompleted(this, new SubmitChangesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SubmitChangesAsync(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ChangeSetEntry> changeSet) {
            this.SubmitChangesAsync(changeSet, null);
        }
        
        public void SubmitChangesAsync(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ChangeSetEntry> changeSet, object userState) {
            if ((this.onBeginSubmitChangesDelegate == null)) {
                this.onBeginSubmitChangesDelegate = new BeginOperationDelegate(this.OnBeginSubmitChanges);
            }
            if ((this.onEndSubmitChangesDelegate == null)) {
                this.onEndSubmitChangesDelegate = new EndOperationDelegate(this.OnEndSubmitChanges);
            }
            if ((this.onSubmitChangesCompletedDelegate == null)) {
                this.onSubmitChangesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSubmitChangesCompleted);
            }
            base.InvokeAsync(this.onBeginSubmitChangesDelegate, new object[] {
                        changeSet}, this.onEndSubmitChangesDelegate, this.onSubmitChangesCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override PandPMobileApp.PandPNameSpace.PandPDomainServicesoap CreateChannel() {
            return new PandPDomainServicesoapClientChannel(this);
        }
        
        private class PandPDomainServicesoapClientChannel : ChannelBase<PandPMobileApp.PandPNameSpace.PandPDomainServicesoap>, PandPMobileApp.PandPNameSpace.PandPDomainServicesoap {
            
            public PandPDomainServicesoapClientChannel(System.ServiceModel.ClientBase<PandPMobileApp.PandPNameSpace.PandPDomainServicesoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetMembers(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetMembers", _args, callback, asyncState);
                return _result;
            }
            
            public PandPMobileApp.PandPNameSpace.QueryResultOfMembers EndGetMembers(System.IAsyncResult result) {
                object[] _args = new object[0];
                PandPMobileApp.PandPNameSpace.QueryResultOfMembers _result = ((PandPMobileApp.PandPNameSpace.QueryResultOfMembers)(base.EndInvoke("GetMembers", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetSysdiagrams(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetSysdiagrams", _args, callback, asyncState);
                return _result;
            }
            
            public PandPMobileApp.PandPNameSpace.QueryResultOfsysdiagrams EndGetSysdiagrams(System.IAsyncResult result) {
                object[] _args = new object[0];
                PandPMobileApp.PandPNameSpace.QueryResultOfsysdiagrams _result = ((PandPMobileApp.PandPNameSpace.QueryResultOfsysdiagrams)(base.EndInvoke("GetSysdiagrams", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetTraffic(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetTraffic", _args, callback, asyncState);
                return _result;
            }
            
            public PandPMobileApp.PandPNameSpace.QueryResultOfTraffic EndGetTraffic(System.IAsyncResult result) {
                object[] _args = new object[0];
                PandPMobileApp.PandPNameSpace.QueryResultOfTraffic _result = ((PandPMobileApp.PandPNameSpace.QueryResultOfTraffic)(base.EndInvoke("GetTraffic", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSubmitChanges(System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ChangeSetEntry> changeSet, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = changeSet;
                System.IAsyncResult _result = base.BeginInvoke("SubmitChanges", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ChangeSetEntry> EndSubmitChanges(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ChangeSetEntry> _result = ((System.Collections.ObjectModel.ObservableCollection<PandPMobileApp.PandPNameSpace.ChangeSetEntry>)(base.EndInvoke("SubmitChanges", _args, result)));
                return _result;
            }
        }
    }
}
